Models/GroomingStaff.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace PetCare_system.Models
{
    public class GroomingStaff
    {

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int GroomStaffId { get; set; }

        [Required]
        [StringLength(50)]
        public string Groom_Name { get; set; }

        [Required]  
        [StringLength(50)]
        public string Groom_Surname { get; set; }

        [Required]  
        [StringLength(50)]
        public string Groom_Email { get;set; }
        public virtual ICollection<Spar_Grooming> SparGroomings { get; set; }
        public GroomingStaff()
        {
            SparGroomings = new HashSet<Spar_Grooming>();
        }


    }
}

Controllers/GroomingStaffsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PetCare_system.Models;

namespace PetCare_system.Controllers
{
    public class GroomingStaffsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: GroomingStaffs
        public ActionResult Index()
        {
            return View(db.GroomingStaffs.ToList());
        }
        // GET: GroomingReport/Report
        // GET: GroomingReport/Report
        [HttpGet]
        // In your GroomingStaffsController.cs
       
        public ActionResult Report()
        {
            // Check if we have a booking in session
            var currentBooking = Session["CurrentBooking"] as dynamic;
            if (currentBooking != null)
            {
                ViewBag.BookingId = currentBooking.BookingId;
                ViewBag.PetName = currentBooking.PetName;
                ViewBag.PetType = $"{currentBooking.PetType} ({currentBooking.Breed})";
                ViewBag.OwnerName = currentBooking.OwnerName;
                ViewBag.GroomingType = currentBooking.ServiceType;
                ViewBag.Email = currentBooking.Email;
                ViewBag.PhoneNumber = currentBooking.PhoneNumber;
                ViewBag.SpecialInstructions = currentBooking.SpecialInstructions;
            }

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Report(FormCollection form)
        {
            // This is a demo - just show success message without saving to database
            TempData["Message"] = "Report have been submitted successfully.";

            // Clear the session for demo purposes
            Session.Remove("CurrentBooking");

            return RedirectToAction("Report");
        }

        [HttpGet]
        public ActionResult GetBookingDetails(int bookingId)
        {
            // Get the booking from the database
            var booking = db.spar_Groomings.FirstOrDefault(b => b.BookingId == bookingId);

            if (booking == null)
            {
                return Json(null, JsonRequestBehavior.AllowGet);
            }

            // Store the booking details in session
            Session["CurrentBooking"] = new
            {
                BookingId = booking.BookingId,
                PetName = booking.PetName,
                PetType = booking.PetType.ToString(),
                Breed = booking.Breed,
                OwnerName = booking.OwnerName,
                ServiceType = booking.ServiceType.ToString(),
                Email = booking.Email,
                PhoneNumber = booking.PhoneNumber,
                SpecialInstructions = booking.SpecialInstructions
            };

            var result = new
            {
                BookingId = booking.BookingId,
                PetName = booking.PetName,
                PetType = $"{booking.PetType.ToString()} ({booking.Breed})",
                OwnerName = booking.OwnerName,
                GroomingType = booking.ServiceType.ToString(),
                Email = booking.Email,
                PhoneNumber = booking.PhoneNumber,
                SpecialInstructions = booking.SpecialInstructions
            };

            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult IndexTwo()
        {
            var groomersWithSessions = db.GroomingStaffs.Include("SparGroomings").ToList();
            return View("IndexTwo", groomersWithSessions);
        }

        // GET: GroomingStaffs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GroomingStaff groomingStaff = db.GroomingStaffs.Find(id);
            if (groomingStaff == null)
            {
                return HttpNotFound();
            }
            return View(groomingStaff);
        }

        // GET: GroomingStaffs/Create
        public ActionResult Create()
        {
            return View(new GroomingStaff());
        }
        // In your GroomingStaffsController.cs

   
// POST: GroomingStaffs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "GroomStaffId,Groom_Name,Groom_Surname,Groom_Email")] GroomingStaff groomingStaff)
        {
            if (ModelState.IsValid)
            {
                db.GroomingStaffs.Add(groomingStaff);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(groomingStaff);
        }

        // GET: GroomingStaffs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GroomingStaff groomingStaff = db.GroomingStaffs.Find(id);
            if (groomingStaff == null)
            {
                return HttpNotFound();
            }
            return View(groomingStaff);
        }

        // POST: GroomingStaffs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "GroomStaffId,Groom_Name,Groom_Surname,Groom_Email")] GroomingStaff groomingStaff)
        {
            if (ModelState.IsValid)
            {
                db.Entry(groomingStaff).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(groomingStaff);
        }

        // GET: GroomingStaffs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GroomingStaff groomingStaff = db.GroomingStaffs.Find(id);
            if (groomingStaff == null)
            {
                return HttpNotFound();
            }
            return View(groomingStaff);
        }

        // POST: GroomingStaffs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            GroomingStaff groomingStaff = db.GroomingStaffs.Find(id);
            db.GroomingStaffs.Remove(groomingStaff);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/GroomingStaffs/Create.cshtml
@model PetCare_system.Models.GroomingStaff

@{
    ViewBag.Title = "Add New Groomer";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid px-4">
    <div class="d-flex justify-content-between align-items-center mb-4">
        <div>
            <h2 class="mb-1"><i class="fas fa-user-plus me-2 text-primary"></i>@ViewBag.Title</h2>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="@Url.Action("Dashboard", "Home")">Dashboard</a></li>
                    <li class="breadcrumb-item"><a href="@Url.Action("Index")">Groomers</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Add New</li>
                </ol>
            </nav>
        </div>
    </div>

    <div class="card shadow-sm">
        <div class="card-header bg-white py-3">
            <h5 class="mb-0"><i class="fas fa-info-circle me-2 text-secondary"></i>Groomer Information</h5>
        </div>
        <div class="card-body">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                @Html.ValidationSummary(true, "", new { @class = "alert alert-danger" })

                <div class="row mb-4">
                    <div class="col-md-6">
                        <div class="form-floating mb-3">
                            @Html.EditorFor(model => model.Groom_Name, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter first name" } })
                            @Html.LabelFor(model => model.Groom_Name, htmlAttributes: new { @class = "form-label" })
                            @Html.ValidationMessageFor(model => model.Groom_Name, "", new { @class = "text-danger small" })
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="form-floating mb-3">
                            @Html.EditorFor(model => model.Groom_Surname, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter last name" } })
                            @Html.LabelFor(model => model.Groom_Surname, htmlAttributes: new { @class = "form-label" })
                            @Html.ValidationMessageFor(model => model.Groom_Surname, "", new { @class = "text-danger small" })
                        </div>
                    </div>
                </div>

                <div class="form-floating mb-4">
                    @Html.EditorFor(model => model.Groom_Email, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter email address" } })
                    @Html.LabelFor(model => model.Groom_Email, htmlAttributes: new { @class = "form-label" })
                    @Html.ValidationMessageFor(model => model.Groom_Email, "", new { @class = "text-danger small" })
                </div>

                <div class="d-flex justify-content-between mt-4">
                    <a href="@Url.Action("Index")" class="btn btn-outline-secondary">
                        <i class="fas fa-arrow-left me-2"></i>Back to List
                    </a>
                    <button type="submit" class="btn btn-primary">
                        <i class="fas fa-save me-2"></i>Create Groomer
                    </button>
                </div>
            }
        </div>
    </div>
</div>

@section Styles {
    <style>
        .form-floating {
            position: relative;
            margin-bottom: 1rem;
        }

            .form-floating label {
                position: absolute;
                top: 0;
                left: 0;
                height: 100%;
                padding: 1rem 0.75rem;
                pointer-events: none;
                border: 1px solid transparent;
                transform-origin: 0 0;
                transition: opacity .1s ease-in-out, transform .1s ease-in-out;
                color: #6c757d;
            }

            .form-floating > .form-control {
                height: calc(3.5rem + 2px);
                padding: 1rem 0.75rem;
            }

                .form-floating > .form-control:focus,
                .form-floating > .form-control:not(:placeholder-shown) {
                    padding-top: 1.625rem;
                    padding-bottom: 0.625rem;
                }

                    .form-floating > .form-control:focus ~ label,
                    .form-floating > .form-control:not(:placeholder-shown) ~ label,
                    .form-floating > .form-select ~ label {
                        opacity: .65;
                        transform: scale(.85) translateY(-0.5rem) translateX(0.15rem);
                    }

        .card {
            border: none;
            border-radius: 0.5rem;
            box-shadow: 0 0.5rem 1rem rgba(0, 0, 0, 0.05);
        }

        .card-header {
            border-bottom: 1px solid rgba(0, 0, 0, 0.05);
        }

        .breadcrumb {
            background-color: transparent;
            padding: 0;
            font-size: 0.875rem;
        }

        .btn {
            padding: 0.5rem 1.25rem;
            border-radius: 0.375rem;
            font-weight: 500;
            transition: all 0.2s;
        }

        .btn-primary {
            background-color: #4361ee;
            border-color: #4361ee;
        }

            .btn-primary:hover {
                background-color: #3a56d4;
                border-color: #3a56d4;
                transform: translateY(-1px);
                box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
            }

        .btn-outline-secondary:hover {
            background-color: #f8f9fa;
        }
    </style>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        // Add animation to form elements
        document.addEventListener('DOMContentLoaded', function () {
            const formElements = document.querySelectorAll('.form-floating');
            formElements.forEach((el, index) => {
                el.style.opacity = '0';
                el.style.transform = 'translateY(20px)';
                el.style.transition = 'opacity 0.3s ease, transform 0.3s ease';
                setTimeout(() => {
                    el.style.opacity = '1';
                    el.style.transform = 'translateY(0)';
                }, 100 * index);
            });
        });
    </script>
}

Views/GroomingStaffs/Delete.cshtml
@model PetCare_system.Models.GroomingStaff

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>GroomingStaff</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Groom_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Groom_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Groom_Surname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Groom_Surname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Groom_Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Groom_Email)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/GroomingStaffs/Details.cshtml
@model PetCare_system.Models.GroomingStaff

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>GroomingStaff</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Groom_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Groom_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Groom_Surname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Groom_Surname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Groom_Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Groom_Email)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.GroomStaffId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/GroomingStaffs/IndexTwo.cshtml
@model IEnumerable<PetCare_system.Models.GroomingStaff>
@using Microsoft.AspNet.Identity

@{
    ViewBag.Title = "Groomers with Assigned Sessions";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid px-4">
    <div class="d-flex justify-content-between align-items-center mb-4">
        <div>
            <h2 class="mb-1"><i class="fas fa-cut me-2 text-primary"></i>@ViewBag.Title</h2>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                 
                    <li class="breadcrumb-item active" aria-current="page">Groomers</li>
                </ol>
            </nav>
        </div>

        <div class="d-flex align-items-center">
            <div class="dropdown me-3">
                <button class="btn btn-outline-secondary dropdown-toggle" type="button" id="userDropdown" data-bs-toggle="dropdown" aria-expanded="false">
                    <i class="fas fa-user-circle me-2"></i>
                    <span class="fw-medium">@User.Identity.GetUserName()</span>
                </button>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="userDropdown">
                    <li><a class="dropdown-item" href="#"><i class="fas fa-user me-2"></i>Profile</a></li>
                  
                    <li><hr class="dropdown-divider"></li>
                    <li>
                        @using (Html.BeginForm("Index", "Home", FormMethod.Post, new { id = "logoutForm" }))
                        {
                            @Html.AntiForgeryToken()
                            <button type="submit" class="dropdown-item text-danger">
                                <i class="fas fa-sign-out-alt me-2"></i>Logout
                            </button>
                        }
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="card shadow-sm mb-4">
        <div class="card-header bg-white py-3">
            <div class="d-flex justify-content-between align-items-center">
                <h5 class="mb-0"><i class="fas fa-list me-2 text-secondary"></i>Groomer Assignments</h5>
                <div>
                   
                   
                </div>
            </div>
        </div>
        <div class="card-body p-0">
            <div class="table-responsive">
                <table class="table table-hover mb-0">
                    <thead class="table-light">
                        <tr>
                            <th class="ps-4">Groomer</th>
                            <th>Contact</th>
                            <th>Assigned Sessions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var groomer in Model)
                        {
                            <tr>
                                <td class="ps-4 align-middle">
                                    <div class="d-flex align-items-center">
                                        <div class="avatar avatar-sm me-3 bg-primary bg-opacity-10 text-primary rounded-circle d-flex align-items-center justify-content-center">
                                            <i class="fas fa-user"></i>
                                        </div>
                                        <div>
                                            <h6 class="mb-0">@groomer.Groom_Name @groomer.Groom_Surname</h6>
                                            <small class="text-muted">ID: @groomer.GroomStaffId</small>
                                        </div>
                                    </div>
                                </td>
                                <td class="align-middle">
                                    <a href="mailto:@groomer.Groom_Email" class="text-reset">
                                        <i class="fas fa-envelope me-2 text-muted"></i>@groomer.Groom_Email
                                    </a>
                                </td>
                                <td>
                                    @if (groomer.SparGroomings != null && groomer.SparGroomings.Any())
                                    {
                                        <div class="accordion" id="sessions-@groomer.GroomStaffId">
                                            @foreach (var session in groomer.SparGroomings)
                                            {
                                                <div class="accordion-item border-0 mb-2">
                                                    <div class="accordion-header">
                                                        <div class="card shadow-sm">
                                                            <div class="card-body p-3">
                                                                <div class="d-flex justify-content-between align-items-center">
                                                                    <div class="d-flex align-items-center">
                                                                        <span class="badge bg-primary bg-opacity-10 text-primary me-3">
                                                                            <i class="fas fa-paw me-1"></i> @session.PetName
                                                                        </span>
                                                                        <small class="text-muted me-3">
                                                                            <i class="far fa-calendar me-1"></i> @session.PreferredDate.ToString("MMM dd, yyyy")
                                                                        </small>
                                                                        <span class="badge @GetServiceTypeBadgeClass(session.ServiceType.ToString())">
                                                                            @session.ServiceType
                                                                        </span>
                                                                    </div>
                                                                    <div>
                                                                        
                                                                        @Html.ActionLink("Report", "Report", "GroomingStaffs",
                                                                            new { bookingId = session.BookingId },
                                                                            new { @class = "btn btn-sm btn-primary" })
                                                                    </div>
                                                                </div>
                                                                @if (!string.IsNullOrEmpty(session.SpecialInstructions))
                                                                {
                                                                    <div class="mt-2 ps-4">
                                                                        <small class="text-muted">
                                                                            <i class="fas fa-info-circle me-1"></i> @session.SpecialInstructions
                                                                        </small>
                                                                    </div>
                                                                }
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            }
                                        </div>
                                    }
                                    else
                                    {
                                        <div class="text-center py-3">
                                            <i class="fas fa-calendar-times fa-2x text-muted mb-2"></i>
                                            <p class="text-muted mb-0">No sessions assigned</p>
                                        </div>
                                    }
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@functions {
    public string GetServiceTypeBadgeClass(string serviceType)
    {
        switch (serviceType)
        {
            case "BasicGrooming":
                return "bg-info bg-opacity-10 text-info";
            case "FullGroomingPackage":
                return "bg-success bg-opacity-10 text-success";
            case "DeluxeSpaTreatment":
                return "bg-warning bg-opacity-10 text-warning";
            case "PuppyKittenFirstVisit":
                return "bg-primary bg-opacity-10 text-primary";
            case "SpecialtyCuts":
                return "bg-purple bg-opacity-10 text-purple";
            default:
                return "bg-secondary bg-opacity-10 text-secondary";
        }
    }
}

@section Scripts {
    <script>
        // Logout confirmation
        document.getElementById('logoutForm')?.addEventListener('submit', function (e) {
            if (!confirm('Are you sure you want to log out?')) {
                e.preventDefault();
            }
        });

        // Initialize tooltips
        $(function () {
            $('[data-bs-toggle="tooltip"]').tooltip();
        });
    </script>
}

<style>
    .avatar {
        width: 36px;
        height: 36px;
        display: inline-flex;
    }

    .bg-purple {
        background-color: #6f42c1;
    }

    .text-purple {
        color: #6f42c1;
    }

    .card {
        border: none;
        border-radius: 0.5rem;
    }

    .accordion-item {
        background: transparent;
    }

    .table th {
        font-weight: 600;
        text-transform: uppercase;
        font-size: 0.75rem;
        letter-spacing: 0.5px;
        border-top: none;
    }

    .badge {
        font-weight: 500;
        padding: 0.35em 0.65em;
    }

    .breadcrumb {
        background: transparent;
        padding: 0;
        font-size: 0.875rem;
    }
</style>

Views/GroomingStaffs/Report.cshtml
@{
    ViewBag.Title = "Create Grooming Report ";
}

<h2>@ViewBag.Title</h2>

@if (TempData["Message"] != null)
{
    <div class="alert alert-info">@TempData["Message"]</div>
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        <label for="BookingId">Booking ID</label>
        <input type="number" name="BookingId" id="BookingId" class="form-control" placeholder="Enter booking ID" required
               onchange="fetchBookingDetails(this.value)"
               value="@ViewBag.BookingId" />
    </div>

    <div class="form-group">
        <label for="PetName">Pet Name</label>
        <input type="text" name="PetName" id="PetName" class="form-control" readonly
               value="@ViewBag.PetName" />
    </div>

    <div class="form-group">
        <label for="PetType">Pet Type/Breed</label>
        <input type="text" name="PetType" id="PetType" class="form-control" readonly
               value="@ViewBag.PetType" />
    </div>

    <div class="form-group">
        <label for="OwnerName">Owner Name</label>
        <input type="text" name="OwnerName" id="OwnerName" class="form-control" readonly
               value="@ViewBag.OwnerName" />
    </div>

    <div class="form-group">
        <label for="GroomingType">Grooming Type</label>
        <input type="text" name="GroomingType" id="GroomingType" class="form-control" readonly
               value="@ViewBag.GroomingType" />
    </div>

    <div class="form-group">
        <label for="Email">Owner Email</label>
        <input type="text" name="Email" id="Email" class="form-control" readonly
               value="@ViewBag.Email" />
    </div>

    <div class="form-group">
        <label for="PhoneNumber">Owner Phone</label>
        <input type="text" name="PhoneNumber" id="PhoneNumber" class="form-control" readonly
               value="@ViewBag.PhoneNumber" />
    </div>

    <!-- Editable report fields -->
    <div class="form-group">
        <label for="Notes">Report Notes</label>
        <textarea name="Notes" id="Notes" class="form-control" rows="5" placeholder="Write report here..." required></textarea>
    </div>

    <div class="form-group form-check">
        <input type="checkbox" class="form-check-input" name="OwnerNotified" id="OwnerNotified" value="true">
        <label class="form-check-label" for="OwnerNotified">Owner notified about any issues</label>
    </div>

    <div class="form-actions">
        <button type="submit" class="btn btn-primary">
            <i class="fas fa-save"></i> Submit Report
        </button>
       
        <a href="@Url.Action("IndexTwo", "GroomingStaffs")" class="btn btn-info">
            <i class="fas fa-home"></i> Return to Home
        </a>
    </div>
}

@section Scripts {
    <script>
        function fetchBookingDetails(bookingId) {
            if (!bookingId) return;

            $.ajax({
                url: '@Url.Action("GetBookingDetails", "GroomingStaffs")',
                type: 'GET',
                data: { bookingId: bookingId },
                success: function (data) {
                    if (data) {
                        $('#BookingId').val(data.BookingId);
                        $('#PetName').val(data.PetName);
                        $('#PetType').val(data.PetType);
                        $('#OwnerName').val(data.OwnerName);
                        $('#GroomingType').val(data.GroomingType);
                        $('#Email').val(data.Email);
                        $('#PhoneNumber').val(data.PhoneNumber);
                        $('#SpecialInstructions').val(data.SpecialInstructions);
                    } else {
                        alert('Booking not found!');
                        clearFields();
                    }
                },
                error: function () {
                    alert('Error fetching booking details');
                    clearFields();
                }
            });
        }

        function clearFields() {
            $('#BookingId').val('');
            $('#PetName').val('');
            $('#PetType').val('');
            $('#OwnerName').val('');
            $('#GroomingType').val('');
            $('#Email').val('');
            $('#PhoneNumber').val('');
            // Don't clear the report fields
        }

        // If we have a booking ID on page load, fetch details
        $(document).ready(function() {
            var bookingId = $('#BookingId').val();
            if (bookingId) {
                fetchBookingDetails(bookingId);
            }
        });
    </script>
}

<style>
    .form-actions {
        margin-top: 20px;
        display: flex;
        gap: 10px;
    }

    .btn i {
        margin-right: 5px;
    }
</style>